deployment:
  image:
    repository: simplewebrtc/signalmaster
  imagePullSecrets: talky-registry
service:
  internalPort: 8888
  internalPortName: websocket
  healthcheckPath: /healthcheck
ingress:
  domain: sandbox.simplewebrtc.com
  tls:
    enabled: true
    secret: simplewebrtc-sandbox
  annotations:
    kubernetes.io/ingress.class: gce
    certmanager.k8s.io/acme-http01-edit-in-place: "true"